on:
  issues:
    types: [opened]

jobs:
  handle_new_issue:
    runs-on: ubuntu-latest
    name: Handle new issue
    steps:
      - name: Greet & Apply label
        uses: themeselection/gh-action-comment-on-new-issue@main
        with:
          message: |
            ### Hi there <img src="https://raw.githubusercontent.com/MartinHeinz/MartinHeinz/master/wave.gif" width="30px">
            Thanks a lot for getting in touch with us. Your support has been raised, our response time could be 1 - 2 business days.
            In the meantime, feel free to check out related issues in the repository for more help. We really appreciate your patience.
      - name: Find duplicates
        uses: wow-actions/potential-duplicates@v1.0.8
        with:
          GITHUB_TOKEN: ${{ github.token }}
          label: duplicate
          comment: >
            Potential duplicates: {{#issues}}
              - #{{ number }} _({{ accuracy }}% Match)_
            {{/issues}}
